### ISSUE TITLE
cam.sc gives you advancements

### ISSUE THREAD

**Issue by ProClifo** [gnembon/scarpet#349] opened 2022-12-16 20:03 UTC
**Describe the bug**
When I'm using the /cam command, it can give me advancements, for example if I go through a stronghold or nether fortress in spectator mode. This shouldn't be possible, as it isn't very survival friendly to get advancements using this script.

**To Reproduce**
1. Clear your advancements: /advancement revoke @s everything
2. Use /cam with the cam.sc script
3. Go to a Nether fortress
4. Receive the advancement [A Terrible Fortress]

**Expected behavior**
I expected not to receive any advancements, since being in spectator mode shouldn't affect your game.

**Environment**
 - Carpet version: fabric-carpet-1.19.2-1.4.84+v221018
 - Minecraft version: 1.19.2

**Comment by CommandLeo** [comment] 2022-12-16 20:08
That's not a bug of the script, it's a Minecraft bug: https://bugs.mojang.com/browse/MC-120083

**Comment by altrisi** [comment] 2023-01-27 12:52
Closing as not an issue of the app.

**Closed by altrisi** 2023-01-27 12:52 UTC
Labels: bug
